### PR TITLE
Added russian language 

### PR DESCRIPTION
**Pull request by buslov**
#2 
I have merged english .lang file from 1.12.1 to master branch to obtain pattern for translations.
It is necessary to contain all strings.

### CODE REVIEW

**Comment by Insane96** [comment]
> I have merged english .lang file from 1.12.1 to master branch to obtain pattern for translations.

Yep, good. I should have done this a while ago. I mean, having 1.12 strings for 1.11 and 1.10 too.

**Comment by Insane96** [comment]
Added manually.

**Comment by Insane96** [comment]
Hey, the mod has been updated and translations needs a slight change.

**Comment by buslov** [comment]
@Insane-96 #12

**Pull request closed without merging**
